#!/usr/bin/env bash

set -e

declare -ra CONTAINERS_NAME=(
	"payment-processor-default"
	"payment-processor-fallback"
	"payment-processor-default-db"
	"payment-processor-fallback-db"
	"rb-2025_cache-aside"
	"rb-2025_health-checker-default"
	"rb-2025_health-checker-fallback"
)

declare -ra MAX_CPU=(
	"1.5"
	"1.5"
	"1.5"
	"1.5"
	"0.5"
	"0.03"
	"0.03"
)

declare -ra MAX_MEMORY=(
	"100m"
	"100m"
	"250m"
	"250m"
	"100m"
	"4m"
	"4m"
)

for (( i = 0; i < ${#CONTAINERS_NAME[@]}; i++ ))
do
	docker update --cpus "${MAX_CPU[$i]}" --memory "${MAX_MEMORY[$i]}" --memory-swap "${MAX_MEMORY[$i]}" "${CONTAINERS_NAME[$i]}"
done
