###########################################################################################

# CPU max: 1.5
# RAM max: 350MB

version: "3.6"

###########################################################################################

x-images-templates:
    app: &app-template
        image: debian:buster-20240612-slim
        build: ..
        depends_on:
            - cache-db
        networks:
            - rb-2025_payment-processor
            - balancer-net
            - data-transfer
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "130MB"

###########################################################################################

networks:
    balancer-net:
        name: rb-2025_balancer-net
        driver: bridge
    data-transfer:
        name: rb-2025_data-transfer
        driver: bridge
    rb-2025_payment-processor:
        external: true

###########################################################################################

services:
    load-balancer:
        image: nginx:1.27.5-alpine3.21-slim
        hostname: "rb-2025_load-balancer"
        container_name: "rb2025-ld" # load balancer
        volumes: # ro = Read Only
            - ./volumes/nginx:/etc/nginx/templates:ro
        depends_on:
            - app-0
            - app-1
        networks:
            - balancer-net
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "30MB"
        environment:
            - NGINX_PORT=9999
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

    cache-db:
        image: valkey/valkey:8.0.4-alpine3.22
        hostname: "rb-2025_cache-db"
        container_name: "rb2025-ca" # cache aside
        ports:
            - "6379:6379"
        networks:
            - data-transfer
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: "60MB"

    app-0:
        <<: *app-template
        hostname: "rb-2025_app-0"
        container_name: "rb2025-a0" # application 0
        ports:
            - "8080:8080"
        environment:
            - PORT=8080

    app-1:
        <<: *app-template
        hostname: "rb-2025_app-1"
        container_name: "rb2025-a1" # application 1
        ports:
            - "8081:8081"
        environment:
            - PORT=8081


###########################################################################################
