#!/bin/sh

# check connection availability of
# the cache data bank
# (timeout in seconds)
./wait-for-it.sh "cache-db:6379" --strict --timeout=255 -- echo "The cache data bank is up!"

# it ensure that all dependences
# are loaded
ldconfig

# start the main program
/app/rb-2025
