###########################################################################################

version: "3.6"

###########################################################################################

networks:
    cache-net:
        name: rb-2025_cache-net
        driver: bridge
    rb-2025_payment-processor:
        external: true

###########################################################################################

x-images-templates:
    health-checker: &health-checker-template
        image: debian:buster-20240612-slim
        build:
            context: ../..
            dockerfile: ./docker/build-files/health-checker.Dockerfile
        depends_on:
            - cache-aside
        networks:
            - rb-2025_payment-processor
            - cache-net

###########################################################################################

services:
    cache-aside:
        image: valkey/valkey:8.0.4-alpine3.22
        hostname: "rb-2025_cache-aside"
        container_name: "rb-2025_cache-aside"
        ports:
            - "6379:6379"
        networks:
            - cache-net

    health-checker-default:
        <<: *health-checker-template
        hostname: "rb-2025_health-checker-default"
        container_name: "rb-2025_health-checker-default"
        command: /app/boot paym-def http://payment-processor-default:8080/payments/service-health
        ports:
            - "9000:8080"

    health-checker-fallback:
        <<: *health-checker-template
        hostname: "rb-2025_health-checker-fallback"
        container_name: "rb-2025_health-checker-fallback"
        command: /app/boot paym-fal http://payment-processor-fallback:8080/payments/service-health
        ports:
            - "9001:8080"

###########################################################################################
